---
- 
  hosts: all
  sudo: True
  user: vagrant
  tasks:
    - 
      name: "Atualiza pacotes"
      shell: sudo apt-get update
    
    - 
      name: "Instala o nginx"
      shell: sudo apt-get install nginx -y
